repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        stages: [pre-commit]
      - id: terraform_trivy
        stages: [pre-push]
        args:
          - --args=--severity HIGH,CRITICAL
          - --args=--skip-dirs="**/.terraform"
          